feat: make synthetic runners use dataframes and rename inputs so stat…
AutoResearch/autora-synthetic pull request #10
Opened 2023-08-18 03:26 UTC by younesStrittmatter

…e logic works

2023-08-29 17:27 UTC, younesStrittmatter commented
also resolves #15

2023-08-29 18:57 UTC, benwandrew requested changes

2023-08-29 18:57 UTC, benwandrew commented on src/autora/experiment_runner/synthetic/psychophysics/weber_fechner_law.py
> +        # We can run the runner with numpy arrays or DataFrames. Ther return value will
```suggestion
        # The runner can accept numpy arrays or pandas DataFrames, but the return value will
```

2023-08-30 18:44 UTC, musslick requested changes
Looks great; just a minor renaming suggestion for the noise in some of the models.

2023-08-30 18:44 UTC, musslick commented on src/autora/experiment_runner/synthetic/economics/expected_value_theory.py
> +            expected_value_A = value_A * probability_a + rng.normal(0, observation_noise)
Would call this `value_noise` which is specific to the expected utility theory instead of `observation_noise`

2023-08-30 18:44 UTC, musslick commented on src/autora/experiment_runner/synthetic/economics/prospect_theory.py
> +            expected_value_A = value_A * probability_a + rng.normal(0, observation_noise)
Same here, I would call `observation_noise` instead `value_noise`

2023-08-30 18:44 UTC, musslick commented on src/autora/experiment_runner/synthetic/psychology/luce_choice_ratio.py
> +            y = (similarity_A1 * focus + rng.normal(0, observation_noise)) / (
I think here it is somewhat fine because we add it at the end and then normalize. You might still want to call it `decision_noise` because it is applied before the division.

2023-09-01 10:45 UTC, musslick approved these changes
Looks great!

2023-09-01 13:08 UTC, benwandrew commented on src/autora/experiment_runner/synthetic/utilities.py
> +    ...         return run(X, std=0.)
just curious, is it normal to include decimal for a float where value is 0 (ie '0,' and not '0')?

2023-09-01 14:53 UTC, younesStrittmatter commented on src/autora/experiment_runner/synthetic/utilities.py
> +    ...         return run(X, std=0.)
I would guess that this has to do with typing. 0. is a float, while 0 is an int. The decimal point "signals" to the user that a float is expected. In other (typed) programming languages, a 0 might even crash when a float is expected. For example, I think 1.234 * 0 crashes in C++ since 1.234 and 0 don't have the same type.

2023-09-01 15:05 UTC, benwandrew approved these changes

2023-09-01 15:05 UTC, merged