feat: add lmm to synthetic experiments
AutoResearch/autora-synthetic pull request #20
Opened 2023-12-07 20:43 UTC by younesStrittmatter

# Description

add linear mixed model synthetic runner

- resolves #19

# Type of change

- **feat**: A new feature

2023-12-11 21:01 UTC, chadcwilliams commented on src/autora/experiment_runner/synthetic/abstract/lmm.py
> +                std_dev = random_effects[group_var].get(part, 0.5)
There is a bug here. 

In the formula, you correctly define the intercept as `1`, but then in your examples you define the intercept as `Intercept`.

For example, 
`formula = 'rt ~ 1 + (1|subject) + x1'` 
`random_effects = {'subject': {'Intercept': .1}}`

This line of code is looking for the key `1` in the random_effects dictionary, which does not exist. I am submitting a PR with a quick fix for this.

2023-12-11 21:25 UTC, chadcwilliams requested changes
I left a comment about a small bug in this, and have created a PR that fixes the bug.

2024-01-11 21:28 UTC, hollandjg approved these changes
Nice!

2024-04-01 14:26 UTC, chadcwilliams approved these changes
Seems great!

2024-04-01 21:35 UTC, merged